name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 17
        uses: actions/setup-node@v4
        with:
          node-version: 17
          cache: "yarn"
      - run: yarn --immutable
      - run: yarn build
      - run: yarn test
